services:
  - type: web
    name: flask-sqlite-app
    env: python
    plan: free  # 使用免费计划
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app  # 用 gunicorn 启动应用
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0  # 指定 Python 版本